name: Backend Continuous Integration

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PIP
        run: pip install pipenv

      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: deps-python-${{ hashFiles('**/Pipfile.lock') }}
        
      - name: INSTALL DEPENDENCIES
        run: |
          pipenv install --dev
          pipenv install flake8

      - name: Run Linter
        run: pipenv run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install pipenv
      
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: deps-python-${{ hashFiles('**/Pipfile.lock') }}

      - name: INSTALL DEPENDENCIES
        run: |
          pipenv install --dev
          pipenv install flake8

      - name: Run Tests
        run: pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pipenv install

      - name: Build Docker Image
        run: docker build --tag mp-backend:latest .
