name: Backend Continous Deployment workflow
on:
  push:
    branches:
      - master 
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install flake8
      
      - name: Run lint
        run: cd starter/backend && pipenv run lint
        

  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install flake8
      
      - name: Run tests
        working-directory: starter/backend
        run: pipenv install pytest && pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{ secrets.AWS_REGION}}
	GITHUB_SHA: ${{ github.sha }}
        
    - name: Logging into ECR
      uses: aws-actions/amazon-ecr-login@v2
  
    - name: Build and Push Docker Image
      working-directory: starter/backend
      run: |
        docker build -t backend:${GITHUB_SHA} .
        docker tag backend:${GITHUB_SHA} 194719225043.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA}
        docker push 194719225043.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA}

    - name: Configuring Kubeconfig
      run:
       aws eks update-kubeconfig --name cluster --region us-east-1


    - name: Updating Kubernetes image
      run: |
        cd ./starter/backend/k8s && kustomize edit set image backend=194719225043.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA}
    
    - name: Apply kubectl
      run: |
        cd ./starter/backend/k8s && kustomize build | kubectl apply -f -
		kubectl get svc -A
